name: Generate header mapping index

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 AM, on day 1 of the month
    - cron: "0 3 1 * *"
jobs:
  build-plan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6     
      - uses: coursier/setup-action@v1
        with:
          apps: scala
          
      # Reuse already resolved info if available
      - uses: actions/cache@v4
        with:
          path: .cache/
          key: gen-mappings-indexer-cache

      - name: Generate mappings
        run: bazel run //index/internal/bcr/indexer --  \
          --output-mappings=$PWD/language/cc/bzldep-index.json \
          --recompute-unresolved \
          --cache-dir=$PWD/.cache \
          -v
        
      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branchName="cron/update-index/$(date +%Y-%m-%d)"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b $branchName
          git add ./language/cc/bzldep-index.json
          
          if git diff --cached --quiet; then
            echo "No changes to the index file, skipping PR creation"
            exit 0
          fi
          
          git commit -m "Automated update of headers index based on bazel-central-registry"
          git push origin $branchName
          
          gh pr create \
            --base=main \
            --head=$branchName \
            --title='[Bot] Update bazel-central-registry headers index' \
            --fill
        